### PR TITLE
Merge the new-ui branch into main

### PR DESCRIPTION
**Pull request by gbenhaim**
The new UI is ready to be integrated into konflux-ci.

### CODE REVIEW

**Comment by avi-biton** [comment]
Login is not possible using the username (user1/user2)
We need to use the email to login (user2@konflux.dev).
Is it expected?

**Comment by gbenhaim** [comment]
| Login is not possible using the username (user1/user2)
We need to use the email to login ([user2@konflux.dev](mailto:user2@konflux.dev)).
Is it expected?

wasn't it always like that?

**Comment by avi-biton** [comment]
> wasn't it always like that?
No, we used to login using the username (user1/user2)

**Comment by gbenhaim** [comment]
@avi-biton I fixed the README.

**Review by avi-biton — APPROVED** [review]
lgtm

**Pull request merged**
