### PR TITLE
feat(KFLUXVNGD-3): automate smee channel creation

### PR DESCRIPTION
**Pull request by yftacherzog**
Randomize the smee channel ID and create the client providing that ID. The ID is stored in a kustomize patch file (ignored by git). The channel will not be created if the patch already exists, so users can store their pre-existing channels in the patch and keep using them.

closes: #169

### CODE REVIEW

**Comment by avi-biton** [comment]
dependencies/smee/smee-channel-id.tpl -> dependencies/smee/smee-channel-id.yaml

**Comment by yftacherzog** [comment]
> dependencies/smee/smee-channel-id.tpl -> dependencies/smee/smee-channel-id.yaml

@avi-biton how do you mean?

**Comment by avi-biton** [comment]
> > dependencies/smee/smee-channel-id.tpl -> dependencies/smee/smee-channel-id.yaml
> 
> @avi-biton how do you mean?

The file extension should be `yaml` 
You also refer to it in the kustomization file:
```
patches:
  - path: smee-channel-id.yaml
```

**Comment by yftacherzog** [comment]
> > > dependencies/smee/smee-channel-id.tpl -> dependencies/smee/smee-channel-id.yaml
> > 
> > 
> > @avi-biton how do you mean?
> 
> The file extension should be `yaml` You also refer to it in the kustomization file:
> 
> ```
> patches:
>   - path: smee-channel-id.yaml
> ```

In git we hold the template (`.tpl`). The script modifies that file and stores the modified file to a `.yaml` file which was added to `.gitignore`.
So, once the script ran, the user will have a .yaml file that was used for deploying the client and from which they can read the value, but that yaml file will not be in git, so the user will not have to worry about it being changed.

**Review by avi-biton — APPROVED** [review]
lgtm

**Pull request merged**
