### PR TITLE
chore(RHTAPWATCH-1044): Run shellcheck on shell scripts

### PR DESCRIPTION
**Pull request by hmariset**
Using Github actions write shellcheck to run on
all the shell scripts.

Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-1044

### CODE REVIEW

**Review by yftacherzog — CHANGES_REQUESTED** [review]
I think we can have the fix to deploy-deps.sh in this PR as well, rather than a different one.

Also, I think shellcheck is preinstalled on the `ubuntu-latest` image that we're using here, so I'd prefer not to rely on a personally-maintained action and instead see if it's going to be any issue running shellcheck directly. Can you give it a try?

**Comment by hmariset** [comment]
> I think we can have the fix to deploy-deps.sh in this PR as well, rather than a different one.
> 
> Also, I think shellcheck is preinstalled on the `ubuntu-latest` image that we're using here, so I'd prefer not to rely on a personally-maintained action and instead see if it's going to be any issue running shellcheck directly. Can you give it a try?

@yftacherzog it worked without using the action and also updated the deploy-deps.sh here

**Comment by yftacherzog** [comment]
> > I think we can have the fix to deploy-deps.sh in this PR as well, rather than a different one.
> > 
> > Also, I think shellcheck is preinstalled on the `ubuntu-latest` image that we're using here, so I'd prefer not to rely on a personally-maintained action and instead see if it's going to be any issue running shellcheck directly. Can you give it a try?
> 
> @yftacherzog it worked without using the action and also updated the deploy-deps.sh here

Looks neat! Did you confirm that the test can fail if you unfix the script that failed the action previously?

**Comment by hmariset** [comment]
> > > I think we can have the fix to deploy-deps.sh in this PR as well, rather than a different one.
> > > Also, I think shellcheck is preinstalled on the `ubuntu-latest` image that we're using here, so I'd prefer not to rely on a personally-maintained action and instead see if it's going to be any issue running shellcheck directly. Can you give it a try?
> > 
> > 
> > @yftacherzog it worked without using the action and also updated the deploy-deps.sh here
> 
> Looks neat! Did you confirm that the test can fail if you unfix the script that failed the action previously?

Yes, I checked that and it's failing if we unfix the script.

**Comment by yftacherzog** [comment]
@gbenhaim I asked @hmariset to give a try to [this action](https://github.com/redhat-plumbers-in-action/differential-shellcheck). I'm seeing now that it's developed by Red Hat people, but doesn't seem to be official Red Hat stuff.

@hmariset also implemented the check on her own, so we can do without that action. Do you think we should use the action or use our own check.

**Comment by gbenhaim** [comment]
I think we should use [differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck)
Major projects already use it - https://github.com/redhat-plumbers-in-action/differential-shellcheck?tab=readme-ov-file#real-life-examples-of-usage

**Comment by yftacherzog** [comment]
> I think we should use [differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck) Major projects already use it - https://github.com/redhat-plumbers-in-action/differential-shellcheck?tab=readme-ov-file#real-life-examples-of-usage

@hmariset could you remove the custom implementation and leave only differential-shellcheck?

**Review by yftacherzog — APPROVED** [review]
lgtm

**Comment by hmariset** [comment]
@gbenhaim @avi-biton can you please review and merge the PR

**Review by yftacherzog — CHANGES_REQUESTED** [review]
@hmariset what's the reason for removing the fix to the existing script?

**Comment by hmariset** [comment]
> @hmariset what's the reason for removing the fix to the existing script?

Differentail shellcheck is only checking the files that are changed in this PR. So, got confused and removed that but I have added that now.

**Review by yftacherzog — APPROVED** [review]

**Pull request merged**
