### PR TITLE
chore: print reason on retry failure

### PR DESCRIPTION
**Pull request by yftacherzog**
Changing the implementation of the retry function so it takes the command to retry and the error message to print if retry fails.

### CODE REVIEW

**Comment by yftacherzog** [comment]
@gbenhaim following the discussion on the other PR. Do you think an approach such as the one in this PR makes sense? It will allow us to keep using unified retry mechanism, while also supporting a customized error message.

**Comment by yftacherzog** [comment]
cc @Omeramsc

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by avi-biton — APPROVED** [review]
LGTM

**Comment by avi-biton** [comment]
I think there is an issue when we use double quotes to pass the parameters to the retry function.
The message I get when adding quotes to this command is (for example):
`kubectl wait --for=condition=Ready --timeout=120s -l app.kubernetes.io/instance=cert-manager -n cert-manager pod: No such file or directory
`

**Pull request merged**
